# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fib_sums(limit)
  last_two_fibonaccis, sum = [1, 2], 2

  while last_two_fibonaccis.last < limit
    last_two_fibonaccis << last_two_fibonaccis.shift + last_two_fibonaccis.first
    sum += last_two_fibonaccis.last if last_two_fibonaccis.last.even?
  end

  sum
end

puts even_fib_sums(4000000)
